import { SCHEMAS } from '@mcschema/core'
import './Collections'
import './schemas/Predicates'
import './schemas/Advancement'
import './schemas/Condition'
import './schemas/LootTable'
import './schemas/Dimension'
import './schemas/TextComponent'
import './schemas/worldgen/Biome'
import './schemas/worldgen/Carver'
import './schemas/worldgen/Feature'
import './schemas/worldgen/ProcessorList'
import './schemas/worldgen/StructureFeature'
import './schemas/worldgen/SurfaceBuilder'
import './schemas/worldgen/TemplatePool'
